/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivilegeRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "balance_diff")]
    pub balance_diff: i32,
    #[serde(rename = "ticket_uid")]
    pub ticket_uid: uuid::Uuid,
    /// Тип операции
    #[serde(rename = "operationType")]
    pub operation_type: String,
}

impl PrivilegeRequest {
    pub fn new(
        username: String,
        balance_diff: i32,
        ticket_uid: uuid::Uuid,
        operation_type: String,
    ) -> PrivilegeRequest {
        PrivilegeRequest {
            username,
            balance_diff,
            ticket_uid,
            operation_type,
        }
    }
}
