apiVersion: v1
kind: Service
metadata:
  name: ticket
  namespace: rsoi
  labels:
    app: ticket
spec:
  selector:
    app: ticket
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070