apiVersion: apps/v1
kind: Deployment
metadata:
  # See: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.service.image.version }}"
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: {{ .Values.service.image.name }}:{{ .Values.service.image.version }}
          env:
            {{ if .Values.service.database.url }}
            - name: DATABASE_URL
              value: "{{ .Values.service.database.url }}"
            {{ end }}

            {{ if .Values.service.listen_address }}
            - name: LISTEN_ADDRESS
              value: "{{ .Values.service.listen_address }}"
            {{ end }}

            {{ if .Values.service.bonus_service_address }}
            - name: BONUS_SERVICE_ADDRESS
              value: "{{ .Values.service.bonus_service_address }}"
            {{ end }}

            {{ if .Values.service.flight_service_address }}
            - name: FLIGHT_SERVICE_ADDRESS
              value: "{{ .Values.service.flight_service_address }}"
            {{ end }}

            {{ if .Values.service.ticket_service_address }}
            - name: TICKET_SERVICE_ADDRESS
              value: "{{ .Values.service.ticket_service_address }}"
            {{ end }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}