apiVersion: v1
kind: Service
metadata:
  name: bonus
  namespace: rsoi
  labels:
    app: bonus
spec:
  selector:
    app: bonus
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050