apiVersion: v1
kind: Service
metadata:
  name: flight
  namespace: rsoi
  labels:
    app: flight
spec:
  selector:
    app: flight
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8060
    targetPort: 8060