apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
  namespace: rsoi
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  name: cG9zdGdyZXM=
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=