apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rsoi
  labels:
    app: postgres
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres