apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: rsoi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: squeakbug73/gateway-service:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: LISTEN_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: listen-address
        - name: BONUS_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: bonus-service-address
        - name: FLIGHT_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: flight-service-address
        - name: TICKET_SERVICE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: ticket-service-address