apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: rsoi
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000